# Generated by Django 4.2.11 on 2024-04-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.country')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('district', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('bath_rooms', models.IntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.city')),
            ],
        ),
    ]
