# Generated by Django 4.2.11 on 2024-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='district',
            field=models.CharField(max_length=30),
        ),
    ]
