# Generated by Django 4.2.11 on 2024-04-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.country'),
        ),
    ]
