# Generated by Django 4.2.11 on 2024-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartmentimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
    ]
