# Generated by Django 4.2.11 on 2024-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
