# Generated by Django 4.2.11 on 2024-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartment_views_alter_apartment_actual_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
