# Generated by Django 4.2.11 on 2024-05-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_apartment_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='district',
        ),
    ]
