# Generated by Django 5.0.4 on 2024-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
